name: Build and Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: dante-ev/cmake-action@v2
      with:
        cmake-version: '3.21.0'

    - name: Install Ninja
      run: sudo apt-get install ninja-build

    - name: Set up build directory
      run: mkdir -p build

    - name: Configure the project with CMake (using Ninja)
      run: cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build the project with Ninja
      run: cd build && cmake --build .

    - name: Run tests
      run: ctest --verbose
